
platform :ios, '12.0'

target 'ZomatoUIKit' do
    use_frameworks!
    
    pod 'ZomatoFoundation', :path => '../ZomatoFoundation/ZomatoFoundation.podspec'
    
end

post_install do |pi|
   pi.pods_project.targets.each do |t|
       t.build_configurations.each do |bc|
           bc.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
       end
   end
end
