
platform :ios, '12.0'

target 'ZomatoFoundation' do
    
    pod 'RxSwift', '6.1.0'
    pod 'RxRelay', '6.1.0'
    
    target 'ZomatoFoundationTests' do
        inherit! :search_paths
        
        pod 'RxBlocking', '6.1.0'
        pod 'RxTest', '6.1.0'
    end
end

post_install do |pi|
   pi.pods_project.targets.each do |t|
       t.build_configurations.each do |bc|
           bc.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
       end
   end
end
